### ISSUE TITLE
Unable to update to new discord.py 1.3.4 version

### ISSUE THREAD

**Issue by DieSteinhose** [Gorialis/discord.py-docker#1]
The current Discord.py version is 1.3.4, but here in the Docker Container/Repo only 1.3.2 runs, I tried to adjust the commad to load 1.3.4. But I do not know how.

`|1 CHECKOUT= RUN INSTALL_TARGET="${CHECKOUT:+"git+https://github.com/Rapptz/discord.py@"}${CHECKOUT}${CHECKOUT:+"#egg="}discord.py[voice,docs]" && echo "Install target: ${INSTALL_TARGET}" && pip install -U "${INSTALL_TARGET}" -q --retries 30 && rm -rf /root/.cache/pip/* && find /usr/local -depth \( \( -type d -a \( -name test -o -name tests \) \) -o \( -type f -a \( -name '*.pyc' -o -name '*.pyo' \) \) \) -exec rm -rf '{}' + && pytest -vs /tmp/tests/runtest.py && rm -rf /tmp/tests && rm -rf /root/.cache/pip/* && find /usr/local -depth \( \( -type d -a \( -name test -o -name tests \) \) -o \( -type f -a \( -name '*.pyc' -o -name '*.pyo' \) \) \) -exec rm -rf '{}' + `

I don't know how to control which version it loads.

Greetings

**Comment by DieSteinhose** [comment]
I have now simply created a dockerfile myself and downloaded it via `RUN pip install docker.py` discord.py.

For those who also have the problem, this is what my dockerfile looks like
```
FROM python:alpine

RUN apk --no-cache add mercurial cloc openssl openssl-dev openssh alpine-sdk bash gettext sudo build-base gnupg linux-headers xz libffi-dev libsodium-dev opus-dev ffmpeg

RUN pip install discord.py

WORKDIR /app 
```

So far this has worked very well. I don't know if there are any packages missing or what else your dockerfile is doing. But for me it is going well at the moment.

**Comment by scarletcafe** [comment]
You are expected to install and update your requirements for your project needs regardless of what image you base off, as while these images do vend packages, I cannot guarantee they will always be the version you need them to be.

At present, pulling any of the images (except potentially 3.9/RC) should give you discord.py 1.3.4. It was previously stuck at 1.3.2 due to build issues with the PyPI version of h5py on 3.8. To increase image layer interoperability, my CI/CD suite does not upload any of the target images unless *every* image successfully completes the build process.

As for your custom Dockerfile, while it works, the point of maintaining this imageset is to guarantee "complete" installs that pass a test suite. Since an image that doesn't pass the test suite won't be uploaded, the images you pull from the Docker Hub repository are *guaranteed* to work, even with CPython extensions, by standard.

You can update your discord.py version (as is the common practice for basing off this image) by changing your Dockerfile to this instead:

```dockerfile
FROM gorialis/discord.py:alpine

RUN pip install --update discord.py

WORKDIR /app
```

This way you don't have to worry about system dependencies, since I have that covered for you, but at the same time can have an updated discord.py even while I'm resolving build errors.
