### ISSUE TITLE
Add discord.py 2.0 Speed Version/orjson support

### ISSUE THREAD

**Issue by Luc1412** [Gorialis/discord.py-docker#3]
I'm using a custom version of the alpine minimal image and currently looking for a way to install orjson. 

The recent addition of rust to the image was caused by the cryptography update from what I know. Unfortunately it's incompatible with orjson. Overall it's a bit tricky to install orjson on alpine Linux due to incompatibility of binary wheels, but there are workarounds when using rustup nightly and providing the right environment variables. 

I got it working to compile on Docker Windows, but not on GH Actions plus the image became 3 times the size of my usual image size.

**Comment by scarletcafe** [comment]
Looking at the repository for the library you're talking about, Rust nightly is **required** for building, so this isn't a workaround, it's the only intended way of installing the module.

Judging by the repository itself, doing the following would be sufficient for installing orjson on effectively any Linux:
```bash
cd $(mktemp -d)  # go to a temporary directory
rustup default nightly-2021-06-24  # refer to https://github.com/ijl/orjson#packaging for the latest recommended nightly
pip wheel --no-binary=orjson orjson  # force manual build
pip install orjson-*.whl  # install build result
rm -rf $(pwd)  # remove temp directory before we leave
cd /app  # go back to whatever we were doing before
```

Running this directly was [sufficient](https://asciinema.org/a/E9rmu6yeHUQaziIZDrh2wJuMI) to install orjson on `alpine-minimal` for me. As far as image size goes, the only thing actually necessary is the wheel (and even that is not necessary once installed), so it would probably come from pip cache, cargo cache, and the extra installed toolchain. pip cache is already cleared as part of my workflow, cargo cache is not cleared (but I should probably implement it), and removing the additional toolchain is easily possible but up to your discretion.

I doubt I will add orjson to the vended modules since I don't imagine it will have usage that will rival the existing ones.
